<a href="https://colab.research.google.com/github/agusarif/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# tampilkan pesan perdana belajar PyTorch
print('Hai! Selamat memulai pembelajaran tentang PyTorch!')

Hai! Selamat memulai pembelajaran tentang PyTorch!


In [2]:
# pilih menu Runtime | Change runtime type | Hardware accelerator: GPU
# uji pemercepat GPU dengan perintah 'magic':
!nvidia-smi

Mon Oct 17 00:42:08 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# 00. Dasar-dasar PyTorch

_Notebook_ sumber: https://www.learnpytorch.io/00_pytorch_fundamentals/

Forum untuk diskusi: https://github.com/mrdbourke/pytorch-deep-learning/discussions

Instalasi PyTorch pada komputer macOS: https://pytorch.org/get-started/locally/

In [1]:
# sertakan pustaka PyTorch dan beberapa pustaka lainnya
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# tampilkan versi dari pustaka PyTorch
print('Versi pustaka PyTorch =', torch.__version__)

Versi pustaka PyTorch = 1.12.1+cu113


## Perkenalan dengan Tensor

### Membuat Tensor

Tensor pada PyTorch dibuat dengan menggunakan metode `torch.tensor()` dengan acuan pada laman: https://pytorch.org/docs/stable/tensors.html

In [2]:
# buat tensor jenis skalar
skalar = torch.tensor(7)
skalar

tensor(7)

In [3]:
# tentukan cacah dimensi (cacah pasangan kurung-siku) dari skalar
skalar.ndim

0

In [4]:
# cuplik nilai asli (bilangan bulat) dari tensor
skalar.item()

7

In [5]:
# buat tensor jenis vektor
vektor = torch.tensor([7, 7])
vektor

tensor([7, 7])

In [6]:
# tentukan cacah dimensi (cacah pasangan kurung-siku) dari vektor
vektor.ndim

1

In [7]:
# tentukan bentuk dari vektor
vektor.shape

torch.Size([2])

In [8]:
# buat tensor jenis matriks
Matriks = torch.tensor([[7, 8],
                        [9, 10]])
Matriks

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# tentukan cacah dimensi (cacah pasangan kurung-siku) dari Matriks
Matriks.ndim

2

In [10]:
# tentukan bentuk dari Matriks
Matriks.shape

torch.Size([2, 2])

In [12]:
# cuplik bagian dari Matriks
Matriks[0]

tensor([7, 8])

In [11]:
# buat tensor yang generik
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [13]:
# tentukan cacah dimensi (cacah pasangan kurung-siku) dari TENSOR
TENSOR.ndim

3

In [14]:
# tentukan bentuk dari TENSOR
TENSOR.shape

torch.Size([2, 3, 3])

In [15]:
# cuplik bagian dari TENSOR
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])